services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nexflow-app
    env_file:
      - .env
    environment:
      DATABASE_URL: postgresql://admin:nexflowadmin@host.docker.internal:5433/nexflow_db?schema=public
      REDIS_URL: redis://host.docker.internal:6379
      HOSTNAME: 0.0.0.0
      PORT: 3000
      NODE_ENV: production
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "3000:3000"
    restart: unless-stopped
